apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gmacastil/apigee-mtls-demo
    sonarqube.org/project-key: apigee-mtls-demo
  description: "Demo configuraci\xF3n mTLS desde Apigee a un Backend"
  name: apigee-mtls-demo
  tags:
  - java
  - apigee
  - mtls
  - backend
spec:
  lifecycle: production
  owner: gmacastil
  system: dummy
  type: service
